### ISSUE TITLE
File integrity check fails

### ISSUE THREAD

**Issue by EmJotGeh** [rotdrop/nextcloud-app-pdf-downloader#2]
Hi,

the file integrity check fails after installation.

**Comment by rotdrop** [comment]
Thanks  for reporting. I'll be on holiday on really offline from 24.07. - 14.08., so this issue will have to wait until then.

**Comment by rotdrop** [comment]
```
root@mailexchange.claus-justus-heine.de:/var/www/cloud/nextcloud# sudo -u www-data php ./occ integrity:check-app pdf_downloader
  - FILE_MISSING:
    - vendor/tecnickcom/tcpdf/tools/.htaccess:
      - expected: 384ad1b42cc64b0a9e82431ddc5330aa02d3f87ef874bdf5bd0ab7933661ba746a2986899f4b39343a8b598cef5b32d775a94fc889badae992dc4ece155ff89d
      - current: 
```
OTOH, in the release tar file the .htaccess is there. So I assume that the NC installer deletes all .htaccess files? Mmmh.
